spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8002

security:
  jwt:
    expiration-time: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/