-- MySQL Script generated by MySQL Workbench
-- Thu Sep 12 13:34:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8 ;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`products` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(255) NOT NULL,
                                                      `price` DOUBLE NOT NULL,
                                                      `stock` INT NOT NULL,
                                                      PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`users` (
                                                   `id` BIGINT NOT NULL,
                                                   `name` VARCHAR(255) NULL,
                                                   `email` VARCHAR(255) NOT NULL,
                                                   `password` VARCHAR(255) NOT NULL,
                                                   `created_at` DATETIME NOT NULL,
                                                   `is_enabled` TINYINT NOT NULL,
                                                   `authorities` VARCHAR(255) NOT NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`shopping_cart` (
                                                           `id` BIGINT NOT NULL,
                                                           `cantidad` VARCHAR(45) NOT NULL,
                                                           `users_id` BIGINT NOT NULL,
                                                           `products_id` BIGINT NOT NULL,
                                                           PRIMARY KEY (`id`, `users_id`, `products_id`),
                                                           INDEX `fk_shopping_cart_users_idx` (`users_id` ASC) VISIBLE,
                                                           INDEX `fk_shopping_cart_products1_idx` (`products_id` ASC) VISIBLE,
                                                           CONSTRAINT `fk_shopping_cart_users`
                                                               FOREIGN KEY (`users_id`)
                                                                   REFERENCES `inventory`.`users` (`id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_shopping_cart_products1`
                                                               FOREIGN KEY (`products_id`)
                                                                   REFERENCES `inventory`.`products` (`id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
